version: '3.8'
services:
  fastapi:
    build:
      context: ./server 
    ports:
      - "8000:8000"
    depends_on:
      - react

  react:
    build:
      context: . 
    ports:
      - "3000:3000"
